### ISSUE TITLE
Deploy to DO automatically

### ISSUE THREAD

**Issue by amrav** [metakgp/metaploy#1]
Options:
1. Do this in a cron job, eg. by checking if we're in a production environment, and `git fetch`ing periodically. Investigate whether this can be done from within Docker.
2. Set up a webhook on the server that Github can ping whenever master is updated.

(Not in the scope of this ticket) Deploying automatically requires confidence that everything will work with the latest changes. We need more tests.

**Comment by proffapt** [comment]
The CD pipeline now exists for both wiki and metaploy :D
